declare module 'kepler.gl'
declare module 'kepler.gl/processors'
declare module 'kepler.gl/actions'
declare module 'kepler.gl/reducers'
declare module 'kepler.gl/react-palm'
declare module 'react-palm/tasks'
