'use client'

import './styles/globals.css'

import { CssBaseline, ThemeProvider } from '@mui/material'
import {theme} from "@/app/styles/theme"
import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns'
import {LocalizationProvider} from "@mui/x-date-pickers"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Data Visualization</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <ThemeProvider theme={theme}>
          <LocalizationProvider dateAdapter={AdapterDateFns}>
        <body id="__next" className="map-background min-h-screen">
          <CssBaseline />
          <main className="">{children}</main>
        </body>
          </LocalizationProvider>
      </ThemeProvider>
    </html>
  )
}
